### ISSUE TITLE
exception creating inbound channel

### ISSUE THREAD

**Issue by chappjc** [companyzero/bisonrelay#62]
```
2022-12-20 09:34:07.267 [INF] GOLB: Fetched server policy. Estimated Invoice amount: 0.0005 DCR
2022-12-20 09:34:14.460 [INF] GOLB: Paying for invoice ...
"payment error: timeout"
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      State.setState (package:flutter/src/widgets/framework.dart:1134)
#1      _NeedsInChannelScreenState.requestRecvCapacity (package:bruig/screens/needs_in_channel.dart:108)
<asynchronous suspension>
```

**Comment by alexlyp** [comment]
believe this has been fixed.
